spring:
  profiles:
    active: dev
---
#各个key的冒号后边必须跟一个空格
server:
  address: localhost
  port: 8080
spring:
  profiles: dev
#数据源信息
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/notification?useSSL=true&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#配置druid连接池
    druid:
      initial-size: 2
      max-active: 10
      min-idle: 1
      max-wait: 60000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
#      validation-query:
#      validation-query-timeout:
      validationQuery: select id from users where id=1;
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
#      time-between-eviction-runs-millis:
      min-evictable-idle-time-millis: 60000
      max-evictable-idle-time-millis: 300000
      filter:
         # 配置StatFilter
        stat:
          db-type: h2
          log-slow-sql: true
          slow-sql-millis: 2000
         # 配置WallFilter
        wall:
          enabled: true
          db-type: h2
          delete-allow: false
          drop-table-allow: false
  jpa:
  #hibernate显示sql语句
    show-sql : true
    database-platform : org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto : none
      naming:
        physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5InnoDBDialect
#配置freemarker
  freemarker:
    request-context-attribute : request
cas:
  signOutFilters: /user/logout
  authFilters: /admin/**
  validateFilters: /admin/**
  requestWrapperFilters: /admin/**
  assertion-filter: /admin/**
  casServerUrlPrefix: https://sso.lihao.com:8443/cas
  casServerLoginUrl: ${cas.casServerUrlPrefix}/login
  casServerLogoutUrl: ${cas.casServerUrlPrefix}/logout
  redirectAfterValidation: true
  useSession: true
  serverName: http://${server.address}:${server.port}
  localServerUrlPrefix: http://${server.address}:${server.port}
  casFilterUrlPattern: /shiro-cas
  localServerLoginUrl: ${cas.serverName}/admin/login
#开发环境配置日志级别
logging:
  level:
    root : info
  path : d:/log
#添加对jsp的支持
#  mvc:
#    view:
#      prefix : /WEB-INF/views/
#      suffix : .jsp
#图片存储位置
myproperties:
  imageroot : static/image
#数据太多时，最多查询多少数据
  limitNumber: 1000
#是否启用redis
  isRedis : no
#支持http关闭springboot
endpoints:
  beans:
    sensitive : false
  shutdown:
    enabled : true
    sensitive : false
