server:
  port: 8092
spring:
  application:
    name: order-webservice
  datasource:
      url: jdbc:mysql://localhost:3306/taobao?useSSL=true&autoReconnect=true
      password: root
      username: root
      driver-class-name: com.mysql.jdbc.Driver
      druid:
        initial-size: 2
        max-active: 10
        min-idle: 1
        max-wait: 60000
        max-pool-prepared-statement-per-connection-size: 20
        pool-prepared-statements: false
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        max-evictable-idle-time-millis: 300000
        min-evictable-idle-time-millis: 60000
dubbo:
  scan:
    base-packages: com.example.taobao.order.webservice
  application:
    name: order-webservice
    id: order-webservice
    qos-enable: true
    qos-port: 22223
  protocol:
    id: order-service
    name: dubbo
    port: 20881
    host: 127.0.0.1
    status: server
  registry:
    address: zookeeper://127.0.0.1:2181
    id: order-webservice-register
mybatis:
  config-location: classpath:config/mybatis/mybatis-config.xml
  mapper-locations: classpath:config/mybatis/mapper/*.xml


