server:
  port: 8092
spring:
  application:
    name: order-webservice
dubbo:
  scan:
    base-packages: com.example.taobao.order.webservice
  application:
    name: order-webservice
    id: order-webservice
    qos-enable: true
    qos-port: 22223
  protocol:
    id: order-service
    name: dubbo
    port: 20881
    host: 127.0.0.1
    status: server
  registry:
    address: zookeeper://127.0.0.1:2181
    id: order-webservice-register

