server:
  port: 8095
spring:
  application:
    name: inventory-webservice
  datasource:
    db1:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/taobao?useSSL=false&autoReconnect=true
      password: root
      username: root
      driver-class-name: com.mysql.jdbc.Driver
      druid:
                initial-size: 2
                max-active: 10
                min-idle: 1
                max-wait: 60000
                max-pool-prepared-statement-per-connection-size: 20
                pool-prepared-statements: false
                test-on-borrow: false
                test-on-return: false
                test-while-idle: true
                max-evictable-idle-time-millis: 300000
                min-evictable-idle-time-millis: 60000
    db2:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/taobao1?useSSL=false&autoReconnect=true
      password: root
      username: root
      driver-class-name: com.mysql.jdbc.Driver
      druid:
                initial-size: 2
                max-active: 10
                min-idle: 1
                max-wait: 60000
                max-pool-prepared-statement-per-connection-size: 20
                pool-prepared-statements: false
                test-on-borrow: false
                test-on-return: false
                test-while-idle: true
                max-evictable-idle-time-millis: 300000
                min-evictable-idle-time-millis: 60000

  redis:
    timeout: 1000
    cluster:
      max-redirects: 5
      nodes: 10.1.11.5:6379,10.1.11.5:6380,10.1.11.5:6381
    pool:
      max-active: 8
      min-idle: 1
      max-idle: 8
      max-wait: 5000

dubbo:
  scan:
    base-packages: com.example.taobao.order.webservice
  application:
    name: inventory-webservice
    id: inventory-webservice
    qos-enable: true
    qos-port: 22224
  protocol:
    id: inventory-service
    name: dubbo
    port: 20883
    host: 127.0.0.1
    status: server
  registry:
    address: zookeeper://127.0.0.1:2181
    id: inventory-webservice-register
mybatis:
  config-location: classpath:config/mybatis/mybatis-config.xml
  mapper-locations: classpath:config/mybatis/mapper/*.xml

redis:
  redisClusterNodes: 10.1.11.5:6379,10.1.11.5:6380,10.1.11.5:6381
  pool:
    maxIdle: 8
    minIdle: 1
    maxTotal: 40
    maxWaitMillis: 5000


