#各个key的冒号后边必须跟一个空格
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    instance-id: ${spring.cloud.client.hostname}:${server.port}

spring:
  application:
    name: PRACTICE-SERVICE-A
server:
  port: 8080

ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 1000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 1500