#各个key的冒号后边必须跟一个空格
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30


spring:
  application:
    name: practice-service-b
  cloud:
    loadbalancer:
      retry:
        enabled: true
server:
  port: 8081

ribbon:
  ReadTimeout: 2000
  ConnectTimeout: 1000
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 2000
management:
  endpoints:
    web:
      exposure:
        exclude: hystrix.stream
